FROM node:20-alpine AS base 

FROM base AS deps 
WORKDIR /app 

COPY package.json package-lock.json ./
COPY packages/ui/package.json ./packages/ui/package.json
COPY packages/db/package.json ./packages/db/package.json
COPY packages/web/package.json ./packages/web/package.json

RUN npm install

FROM base AS builder 
WORKDIR /app 
COPY --from=deps /app/node_modules ./node_modules
COPY . . 

RUN npm run db:generate

RUN npm run build

FROM base AS runner 
WORKDIR /app 

ENV NODE_ENV production

RUN addgroup --system -gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/apps/web/public ./apps/web/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "apps/web/server.js"]