FROM node:20-alpine AS base 

RUN apk add --no-cache openssl

FROM base AS deps 
WORKDIR /app 

COPY package.json package-lock.json ./
COPY turbo.json ./
COPY packages/ui/package.json ./packages/ui/package.json
COPY packages/db/package.json ./packages/db/package.json
COPY apps/http-backend/package.json ./apps/http-backend/package.json
COPY apps/upload-worker/package.json ./apps/upload-worker/package.json
COPY apps/wsServer/package.json ./apps/wsServer/package.json
COPY apps/web/package.json ./apps/web/package.json

RUN npm install

FROM base AS builder 
WORKDIR /app 
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run db:generate

RUN npm run build


CMD ["npm", "run", "start-web"]
